<?php

namespace Database\Seeders\Catalogue;

use App\Models\Catalogue\Note;
use Illuminate\Database\Seeder;

class NoteSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['slug' => 'aldehydes', 'name' => ['uk' => 'Альдегіди', 'en' => 'Aldehydes']],
            ['slug' => 'almond', 'name' => ['uk' => 'Мигдаль', 'en' => 'Almond']],
            ['slug' => 'amber', 'name' => ['uk' => 'Амбра', 'en' => 'Amber']],
            ['slug' => 'ambrofix', 'name' => ['uk' => 'Амброфікс', 'en' => 'Ambrofix']],
            ['slug' => 'ambroxan', 'name' => ['uk' => 'Амброксан', 'en' => 'Ambroxan']],
            ['slug' => 'bay-leaves', 'name' => ['uk' => 'Листя лавра', 'en' => 'Bay leaves']],
            ['slug' => 'benzoin', 'name' => ['uk' => 'Бензоїн', 'en' => 'Benzoin']],
            ['slug' => 'bergamot', 'name' => ['uk' => 'Бергамот', 'en' => 'Bergamot']],
            ['slug' => 'birch', 'name' => ['uk' => 'Береза', 'en' => 'Birch']],
            ['slug' => 'bitter-almond', 'name' => ['uk' => 'Гіркий мигдаль', 'en' => 'Bitter almond']],
            ['slug' => 'black-cherry', 'name' => ['uk' => 'Чорна вишня', 'en' => 'Black cherry']],
            ['slug' => 'black-pepper', 'name' => ['uk' => 'Чорний перець', 'en' => 'Black pepper']],
            ['slug' => 'blackcurrant', 'name' => ['uk' => 'Чорна смородина', 'en' => 'Blackcurrant']],
            ['slug' => 'boxwood', 'name' => ['uk' => 'Самшит', 'en' => 'Boxwood']],
            ['slug' => 'caramel', 'name' => ['uk' => 'Карамель', 'en' => 'Caramel']],
            ['slug' => 'cashmere-wood', 'name' => ['uk' => 'Кашемірове дерево', 'en' => 'Cashmere wood']],
            ['slug' => 'cedar', 'name' => ['uk' => 'Кедр', 'en' => 'Cedar']],
            ['slug' => 'cinnamon', 'name' => ['uk' => 'Кориця', 'en' => 'Cinnamon']],
            ['slug' => 'clementine', 'name' => ['uk' => 'Клементин', 'en' => 'Clementine']],
            ['slug' => 'cocoa', 'name' => ['uk' => 'Какао', 'en' => 'Cocoa']],
            ['slug' => 'coffee', 'name' => ['uk' => 'Кава', 'en' => 'Coffee']],
            ['slug' => 'cognac', 'name' => ['uk' => 'Коньяк', 'en' => 'Cognac']],
            ['slug' => 'cyclamen', 'name' => ['uk' => 'Цикламен', 'en' => 'Cyclamen']],
            ['slug' => 'davana', 'name' => ['uk' => 'Давана', 'en' => 'Davana']],
            ['slug' => 'fennel', 'name' => ['uk' => 'Фенхель', 'en' => 'Fennel']],
            ['slug' => 'fig', 'name' => ['uk' => 'Інжир', 'en' => 'Fig']],
            ['slug' => 'frankincense', 'name' => ['uk' => 'Ладан', 'en' => 'Frankincense']],
            ['slug' => 'geranium', 'name' => ['uk' => 'Герань', 'en' => 'Geranium']],
            ['slug' => 'ginger', 'name' => ['uk' => 'Імбир', 'en' => 'Ginger']],
            ['slug' => 'grapefruit', 'name' => ['uk' => 'Грейпфрут', 'en' => 'Grapefruit']],
            ['slug' => 'green-freshness', 'name' => ['uk' => 'Зелена свіжість', 'en' => 'Green freshness']],
            ['slug' => 'guaiac', 'name' => ['uk' => 'Гваякове дерево', 'en' => 'Guaiac wood']],
            ['slug' => 'hazelnut', 'name' => ['uk' => 'Фундук', 'en' => 'Hazelnut']],
            ['slug' => 'hyacinth', 'name' => ['uk' => 'Гіацинт', 'en' => 'Hyacinth']],
            ['slug' => 'immortelle', 'name' => ['uk' => 'Іммортель', 'en' => 'Immortelle']],
            ['slug' => 'iris', 'name' => ['uk' => 'Ірис', 'en' => 'Iris']],
            ['slug' => 'jasmine', 'name' => ['uk' => 'Жасмин', 'en' => 'Jasmine']],
            ['slug' => 'labdanum', 'name' => ['uk' => 'Лабданум', 'en' => 'Labdanum']],
            ['slug' => 'lavender', 'name' => ['uk' => 'Лаванда', 'en' => 'Lavender']],
            ['slug' => 'lemon', 'name' => ['uk' => 'Лимон', 'en' => 'Lemon']],
            ['slug' => 'lily-of-the-valley', 'name' => ['uk' => 'Конвалія', 'en' => 'Lily of the valley']],
            ['slug' => 'lychee', 'name' => ['uk' => 'Лічі', 'en' => 'Lychee']],
            ['slug' => 'mandarin', 'name' => ['uk' => 'Мандарин', 'en' => 'Mandarin']],
            ['slug' => 'maracuja', 'name' => ['uk' => 'Маракуя', 'en' => 'Passion fruit']],
            ['slug' => 'marigold', 'name' => ['uk' => 'Чорнобривці', 'en' => 'Marigold']],
            ['slug' => 'marine-accord', 'name' => ['uk' => 'Морський акорд', 'en' => 'Marine accord']],
            ['slug' => 'matcha', 'name' => ['uk' => 'Матча зеленого чаю', 'en' => 'Matcha']],
            ['slug' => 'mineral', 'name' => ['uk' => 'Мінерал', 'en' => 'Mineral']],
            ['slug' => 'musk', 'name' => ['uk' => 'Мускус', 'en' => 'Musk']],
            ['slug' => 'neroli', 'name' => ['uk' => 'Нероль', 'en' => 'Neroli']],
            ['slug' => 'nut-tree', 'name' => ['uk' => 'Горіхове дерево', 'en' => 'Nut tree']],
            ['slug' => 'oak', 'name' => ['uk' => 'Дуб', 'en' => 'Oak']],
            ['slug' => 'oakmoss', 'name' => ['uk' => 'Дубовий мох', 'en' => 'Oakmoss']],
            ['slug' => 'orange', 'name' => ['uk' => 'Апельсин', 'en' => 'Orange']],
            ['slug' => 'osmanthus', 'name' => ['uk' => 'Османтус', 'en' => 'Osmanthus']],
            ['slug' => 'oud', 'name' => ['uk' => 'Уд', 'en' => 'Oud']],
            ['slug' => 'patchouli', 'name' => ['uk' => 'Пачулі', 'en' => 'Patchouli']],
            ['slug' => 'peach', 'name' => ['uk' => 'Персик', 'en' => 'Peach']],
            ['slug' => 'pear', 'name' => ['uk' => 'Груша', 'en' => 'Pear']],
            ['slug' => 'peony', 'name' => ['uk' => 'Півонія', 'en' => 'Peony']],
            ['slug' => 'pepper', 'name' => ['uk' => 'Перець', 'en' => 'Pepper']],
            ['slug' => 'peruvian-balsam', 'name' => ['uk' => 'Перуанський бальзам', 'en' => 'Peruvian balsam']],
            ['slug' => 'pineapple', 'name' => ['uk' => 'Ананас', 'en' => 'Pineapple']],
            ['slug' => 'pink-pepper', 'name' => ['uk' => 'Рожевий перець', 'en' => 'Pink pepper']],
            ['slug' => 'praline', 'name' => ['uk' => 'Пралине', 'en' => 'Praline']],
            ['slug' => 'raspberry', 'name' => ['uk' => 'Малина', 'en' => 'Raspberry']],
            ['slug' => 'resin', 'name' => ['uk' => 'Смола', 'en' => 'Resin']],
            ['slug' => 'rose', 'name' => ['uk' => 'Троянда', 'en' => 'Rose']],
            ['slug' => 'rum', 'name' => ['uk' => 'Ром', 'en' => 'Rum']],
            ['slug' => 'saffron', 'name' => ['uk' => 'Шафран', 'en' => 'Saffron']],
            ['slug' => 'sandalwood', 'name' => ['uk' => 'Сандал', 'en' => 'Sandalwood']],
            ['slug' => 'styrax', 'name' => ['uk' => 'Стиракс', 'en' => 'Styrax']],
            ['slug' => 'suede', 'name' => ['uk' => 'Замша', 'en' => 'Suede']],
            ['slug' => 'tobacco', 'name' => ['uk' => 'Тютюн', 'en' => 'Tobacco']],
            ['slug' => 'tolu-balsam', 'name' => ['uk' => 'Толубальзам', 'en' => 'Tolu balsam']],
            ['slug' => 'tonka-bean', 'name' => ['uk' => 'Тонка боб', 'en' => 'Tonka bean']],
            ['slug' => 'tuberose', 'name' => ['uk' => 'Тубероза', 'en' => 'Tuberose']],
            ['slug' => 'turkish-rose', 'name' => ['uk' => 'Турецька троянда', 'en' => 'Turkish rose']],
            ['slug' => 'vanilla', 'name' => ['uk' => 'Ваніль', 'en' => 'Vanilla']],
            ['slug' => 'verbena', 'name' => ['uk' => 'Вербена', 'en' => 'Verbena']],
            ['slug' => 'vetiver', 'name' => ['uk' => 'Ветивер', 'en' => 'Vetiver']],
            ['slug' => 'violet', 'name' => ['uk' => 'Фіалка', 'en' => 'Violet']],
            ['slug' => 'wheat', 'name' => ['uk' => 'Пшениця', 'en' => 'Wheat']],
            ['slug' => 'white-musk', 'name' => ['uk' => 'Білий мускус', 'en' => 'White musk']],
            ['slug' => 'woody-notes', 'name' => ['uk' => 'Деревні ноти', 'en' => 'Woody notes']],
        ];

        foreach ($rows as $i => $r) {
            Note::updateOrCreate(['slug' => $r['slug']], array_merge($r, ['sort_order' => $i, 'is_active' => true]));
        }
    }
}
